# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def default_pods
    pod 'Alamofire', '~> 4.0'
    pod 'Crashlytics'
    pod 'ReachabilitySwift', '~> 3'
        
    # pod 'HastenMenu', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
    pod 'HastenWS', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
    # pod 'HastenRepositoryManager', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
    # pod 'HastenCore/Core', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
    # pod 'HastenCore/Twitter', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
    # pod 'HastenCore/Facebook', :git => 'git@bitbucket.org:grupohasten/hastencore-ios.git', :branch => 'develop'
end

pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

target ‘inproecoApp’ do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    default_pods
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
